package com.example.model

import com.example.R
import com.example.ui.theme.*
import androidx.compose.ui.graphics.Color

enum class Category(
  val id: String,
  val titleSw: String,
  val titleEn: String,
  val emoji: String,
  val tag: String,
  val accentColor: Color,
  val lightBg: Color,
) {
  GREETINGS(
    id = "greetings",
    titleSw = "Salamu",
    titleEn = "Greetings",
    emoji = "👋",
    tag = "KICD Strand 1",
    accentColor = SafariSecondary,
    lightBg = SoftGreenCardBg,
  ),
  ANIMALS(
    id = "animals",
    titleSw = "Wanyama",
    titleEn = "Animals",
    emoji = "🦁",
    tag = "KICD Strand 2",
    accentColor = SavannaPrimaryContainer,
    lightBg = WarmCardBg,
  ),
  NUMBERS(
    id = "numbers",
    titleSw = "Hesabu 1–10",
    titleEn = "Numbers 1–10",
    emoji = "🔢",
    tag = "KICD Strand 3",
    accentColor = SunOrangeTertiary,
    lightBg = SoftPinkCardBg,
  ),
  FAMILY(
    id = "family",
    titleSw = "Familia",
    titleEn = "Family",
    emoji = "👨‍👩‍👧‍👦",
    tag = "KICD Strand 4",
    accentColor = SavannaPrimary,
    lightBg = WarmCardBg,
  ),
  BODY(
    id = "body",
    titleSw = "Mwili Wangu",
    titleEn = "My Body",
    emoji = "👀",
    tag = "KICD Strand 5",
    accentColor = SafariSecondary,
    lightBg = SoftBlueCardBg,
  ),
  COLORS(
    id = "colors",
    titleSw = "Rangi",
    titleEn = "Colors",
    emoji = "🎨",
    tag = "KICD Strand 6",
    accentColor = SunOrangeTertiaryContainer,
    lightBg = SoftPurpleCardBg,
  ),
  SCHOOL(
    id = "school",
    titleSw = "Shuleni na Nyumbani",
    titleEn = "School & Home",
    emoji = "📚",
    tag = "KICD Strand 7",
    accentColor = SavannaPrimary,
    lightBg = SoftBlueCardBg,
  ),
  FOOD(
    id = "food",
    titleSw = "Chakula na Matunda",
    titleEn = "Food & Fruits",
    emoji = "🍌",
    tag = "KICD Strand 8",
    accentColor = SunOrangeTertiary,
    lightBg = WarmCardBg,
  );
}

data class Flashcard(
  val id: String,
  val english: String,
  val kiswahili: String,
  val syllables: String,
  val category: Category,
  val emoji: String,
  val exampleSentenceEn: String,
  val exampleSentenceSw: String,
  val funFact: String,
)

data class Sticker(
  val id: String,
  val nameSw: String,
  val nameEn: String,
  val badgeText: String,
  val cheerText: String,
  val isUnlocked: Boolean,
  val drawableRes: Int,
  val requirementText: String = "",
)

object VocabularyRepository {
  val flashcards: List<Flashcard> = listOf(
    // Salamu / Greetings
    Flashcard(
      id = "greet_1",
      english = "Hello",
      kiswahili = "Jambo / Hujambo",
      syllables = "HU • JA • MBO",
      category = Category.GREETINGS,
      emoji = "👋",
      exampleSentenceEn = "Hello friend! Nice to meet you.",
      exampleSentenceSw = "Hujambo rafiki yangu!",
      funFact = "In Kenya, children greet elders respectfully with 'Shikamoo!'",
    ),
    Flashcard(
      id = "greet_2",
      english = "Thank you",
      kiswahili = "Asante",
      syllables = "A • SA • NTE",
      category = Category.GREETINGS,
      emoji = "🙏",
      exampleSentenceEn = "Thank you for the sweet mango.",
      exampleSentenceSw = "Asante kwa embe tamu.",
      funFact = "'Asante sana' means 'Thank you very much!'",
    ),
    Flashcard(
      id = "greet_3",
      english = "How are you?",
      kiswahili = "Habari?",
      syllables = "HA • BA • RI",
      category = Category.GREETINGS,
      emoji = "😊",
      exampleSentenceEn = "How are you this morning?",
      exampleSentenceSw = "Habari ya asubuhi?",
      funFact = "A cheerful reply to 'Habari' is 'Nzuri!' (Good!)",
    ),
    Flashcard(
      id = "greet_4",
      english = "Goodbye",
      kiswahili = "Kwa heri",
      syllables = "KWA • HE • RI",
      category = Category.GREETINGS,
      emoji = "🙋",
      exampleSentenceEn = "Goodbye teacher, see you tomorrow!",
      exampleSentenceSw = "Kwa heri mwalimu, tutaonana kesho!",
      funFact = "'Heri' means good fortune and peace.",
    ),
    Flashcard(
      id = "greet_5",
      english = "Welcome",
      kiswahili = "Karibu",
      syllables = "KA • RI • BU",
      category = Category.GREETINGS,
      emoji = "🏡",
      exampleSentenceEn = "Welcome to our home!",
      exampleSentenceSw = "Karibu nyumbani kwetu!",
      funFact = "Say 'Karibuni' when welcoming more than one person!",
    ),

    // Wanyama / Animals
    Flashcard(
      id = "anim_1",
      english = "Lion",
      kiswahili = "Simba",
      syllables = "SI • MBA",
      category = Category.ANIMALS,
      emoji = "🦁",
      exampleSentenceEn = "The lion is the king of the savanna.",
      exampleSentenceSw = "Simba ni mfalme wa mbugani.",
      funFact = "A lion's roar can be heard 8 kilometers away!",
    ),
    Flashcard(
      id = "anim_2",
      english = "Giraffe",
      kiswahili = "Twiga",
      syllables = "TWI • GA",
      category = Category.ANIMALS,
      emoji = "🦒",
      exampleSentenceEn = "Twiga is our tall friendly mascot!",
      exampleSentenceSw = "Twiga ni mnyama mrefu mwenye tabasamu!",
      funFact = "Twiga is Kenya's beloved national animal emblem.",
    ),
    Flashcard(
      id = "anim_3",
      english = "Elephant",
      kiswahili = "Tembo",
      syllables = "TE • MBO",
      category = Category.ANIMALS,
      emoji = "🐘",
      exampleSentenceEn = "The elephant has big ears and a long trunk.",
      exampleSentenceSw = "Tembo ana masikio makubwa na mkonga mrefu.",
      funFact = "In Kiswahili, an elephant is also called 'Ndovu'.",
    ),
    Flashcard(
      id = "anim_4",
      english = "Dog",
      kiswahili = "Mbwa",
      syllables = "M • BWA",
      category = Category.ANIMALS,
      emoji = "🐕",
      exampleSentenceEn = "The dog barks joyfully.",
      exampleSentenceSw = "Mbwa anabweka kwa furaha.",
      funFact = "Mbwa is human's loyal friend on the shamba!",
    ),
    Flashcard(
      id = "anim_5",
      english = "Cat",
      kiswahili = "Paka",
      syllables = "PA • KA",
      category = Category.ANIMALS,
      emoji = "🐱",
      exampleSentenceEn = "The cat likes drinking fresh milk.",
      exampleSentenceSw = "Paka anapenda kunywa maziwa safi.",
      funFact = "Paka purrs 'ngurr-ngurr' when gentle and happy!",
    ),
    Flashcard(
      id = "anim_6",
      english = "Hare / Rabbit",
      kiswahili = "Sungura",
      syllables = "SU • NGU • RA",
      category = Category.ANIMALS,
      emoji = "🐰",
      exampleSentenceEn = "Sungura is clever and very fast.",
      exampleSentenceSw = "Sungura ni mjanja na mwepesi sana.",
      funFact = "Sungura Mjanja is the hero of many East African folktales!",
    ),
    Flashcard(
      id = "anim_7",
      english = "Chicken",
      kiswahili = "Kuku",
      syllables = "KU • KU",
      category = Category.ANIMALS,
      emoji = "🐔",
      exampleSentenceEn = "The chicken lays eggs in the morning.",
      exampleSentenceSw = "Kuku anataga mayai asubuhi.",
      funFact = "Baby chicks are called 'Vifaranga' in Kiswahili.",
    ),

    // Hesabu / Numbers 1-10
    Flashcard(
      id = "num_1",
      english = "One (1)",
      kiswahili = "Moja",
      syllables = "MO • JA",
      category = Category.NUMBERS,
      emoji = "1️⃣",
      exampleSentenceEn = "I have one nose.",
      exampleSentenceSw = "Nina pua moja.",
      funFact = "Moja starts every count in Kenya!",
    ),
    Flashcard(
      id = "num_2",
      english = "Two (2)",
      kiswahili = "Mbili",
      syllables = "MBI • LI",
      category = Category.NUMBERS,
      emoji = "2️⃣",
      exampleSentenceEn = "I have two bright eyes.",
      exampleSentenceSw = "Nina macho mawili.",
      funFact = "Mbili sounds like 'm-bee-lee'.",
    ),
    Flashcard(
      id = "num_3",
      english = "Three (3)",
      kiswahili = "Tatu",
      syllables = "TA • TU",
      category = Category.NUMBERS,
      emoji = "3️⃣",
      exampleSentenceEn = "There are three birds in the acacia tree.",
      exampleSentenceSw = "Kuna ndege watatu mtini.",
      funFact = "Tatu forms a strong triangle!",
    ),
    Flashcard(
      id = "num_4",
      english = "Four (4)",
      kiswahili = "Nne",
      syllables = "N • NE",
      category = Category.NUMBERS,
      emoji = "4️⃣",
      exampleSentenceEn = "The car has four wheels.",
      exampleSentenceSw = "Gari lina magurudumu manne.",
      funFact = "Notice the double 'n' in Nne!",
    ),
    Flashcard(
      id = "num_5",
      english = "Five (5)",
      kiswahili = "Tano",
      syllables = "TA • NO",
      category = Category.NUMBERS,
      emoji = "5️⃣",
      exampleSentenceEn = "High five! Give me five fingers!",
      exampleSentenceSw = "Piga tano! Vidole vitano!",
      funFact = "'Piga tano' is Kiswahili for 'Give me a high-five'!",
    ),
    Flashcard(
      id = "num_6",
      english = "Six (6)",
      kiswahili = "Sita",
      syllables = "SI • TA",
      category = Category.NUMBERS,
      emoji = "6️⃣",
      exampleSentenceEn = "Six delicious sweet bananas.",
      exampleSentenceSw = "Ndizi sita tamu sana.",
      funFact = "Sita is an Arabic loanword embraced in Kiswahili.",
    ),
    Flashcard(
      id = "num_7",
      english = "Seven (7)",
      kiswahili = "Saba",
      syllables = "SA • BA",
      category = Category.NUMBERS,
      emoji = "7️⃣",
      exampleSentenceEn = "There are seven days in a week.",
      exampleSentenceSw = "Kuna siku saba kwa wiki.",
      funFact = "Saba-Saba is a famous day in East African history!",
    ),
    Flashcard(
      id = "num_8",
      english = "Eight (8)",
      kiswahili = "Nane",
      syllables = "NA • NE",
      category = Category.NUMBERS,
      emoji = "8️⃣",
      exampleSentenceEn = "The spider has eight legs.",
      exampleSentenceSw = "Buibui ana miguu minane.",
      funFact = "Nane-Nane honors farmers in East Africa.",
    ),
    Flashcard(
      id = "num_9",
      english = "Nine (9)",
      kiswahili = "Tisa",
      syllables = "TI • SA",
      category = Category.NUMBERS,
      emoji = "9️⃣",
      exampleSentenceEn = "Nine stars shining in the night sky.",
      exampleSentenceSw = "Nyota tisa zinamulika angani.",
      funFact = "Tisa is the highest single-digit number!",
    ),
    Flashcard(
      id = "num_10",
      english = "Ten (10)",
      kiswahili = "Kumi",
      syllables = "KU • MI",
      category = Category.NUMBERS,
      emoji = "🔟",
      exampleSentenceEn = "I have ten fingers and ten toes.",
      exampleSentenceSw = "Nina vidole kumi vya mikono.",
      funFact = "Kumi means you reached the double digits!",
    ),

    // Familia / Family
    Flashcard(
      id = "fam_1",
      english = "Mother",
      kiswahili = "Mama",
      syllables = "MA • MA",
      category = Category.FAMILY,
      emoji = "👩",
      exampleSentenceEn = "Mother gives the warmest hugs.",
      exampleSentenceSw = "Mama ananipenda sana.",
      funFact = "Mama is one of the first words spoken worldwide!",
    ),
    Flashcard(
      id = "fam_2",
      english = "Father",
      kiswahili = "Baba",
      syllables = "BA • BA",
      category = Category.FAMILY,
      emoji = "👨",
      exampleSentenceEn = "Father tells joyful bedtime stories.",
      exampleSentenceSw = "Baba anasimulia hadithi za kupendeza.",
      funFact = "Baba works hard with a caring heart.",
    ),
    Flashcard(
      id = "fam_3",
      english = "Brother",
      kiswahili = "Kaka",
      syllables = "KA • KA",
      category = Category.FAMILY,
      emoji = "👦",
      exampleSentenceEn = "My brother plays football with me.",
      exampleSentenceSw = "Kaka yangu anacheza soka nami.",
      funFact = "'Kaka' is also used warmly for a close friend.",
    ),
    Flashcard(
      id = "fam_4",
      english = "Sister",
      kiswahili = "Dada",
      syllables = "DA • DA",
      category = Category.FAMILY,
      emoji = "👧",
      exampleSentenceEn = "My sister sings sweet songs.",
      exampleSentenceSw = "Dada yangu anaimba nyimbo nzuri.",
      funFact = "'Dada' cares and helps with homework.",
    ),
    Flashcard(
      id = "fam_5",
      english = "Baby / Child",
      kiswahili = "Mtoto",
      syllables = "MTO • TO",
      category = Category.FAMILY,
      emoji = "👶",
      exampleSentenceEn = "The baby sleeps peacefully.",
      exampleSentenceSw = "Mtoto analala kwa amani.",
      funFact = "Plural is 'Watoto' (children)!",
    ),
    Flashcard(
      id = "fam_6",
      english = "Grandmother",
      kiswahili = "Nyanya / Bibi",
      syllables = "NYA • NYA",
      category = Category.FAMILY,
      emoji = "👵",
      exampleSentenceEn = "Grandmother cooks delicious uji.",
      exampleSentenceSw = "Nyanya anapika uji mtamu sana.",
      funFact = "In Coastal Swahili, she is also called 'Bibi'.",
    ),
    Flashcard(
      id = "fam_7",
      english = "Grandfather",
      kiswahili = "Babu",
      syllables = "BA • BU",
      category = Category.FAMILY,
      emoji = "👴",
      exampleSentenceEn = "Babu shares wise stories of old times.",
      exampleSentenceSw = "Babu anatoa hekima na hadithi za kale.",
      funFact = "Grandpa's walking stick is 'bakora'.",
    ),

    // Mwili / Body
    Flashcard(
      id = "body_1",
      english = "Head",
      kiswahili = "Kichwa",
      syllables = "KI • CHWA",
      category = Category.BODY,
      emoji = "🧒",
      exampleSentenceEn = "Nod your head up and down!",
      exampleSentenceSw = "Tikisa kichwa chako juu na chini!",
      funFact = "Twiga wears a sunny safari hat on his kichwa!",
    ),
    Flashcard(
      id = "body_2",
      english = "Eyes",
      kiswahili = "Macho",
      syllables = "MA • CHO",
      category = Category.BODY,
      emoji = "👀",
      exampleSentenceEn = "I see the beautiful savanna with my eyes.",
      exampleSentenceSw = "Ninaona uzuri kwa macho yangu.",
      funFact = "One eye is called 'Jicho'!",
    ),
    Flashcard(
      id = "body_3",
      english = "Nose",
      kiswahili = "Pua",
      syllables = "PU • A",
      category = Category.BODY,
      emoji = "👃",
      exampleSentenceEn = "I smell sweet flowers with my nose.",
      exampleSentenceSw = "Ninanusa maua kwa pua yangu.",
      funFact = "Tembo has the longest pua in the animal kingdom!",
    ),
    Flashcard(
      id = "body_4",
      english = "Mouth",
      kiswahili = "Mdomo",
      syllables = "MDO • MO",
      category = Category.BODY,
      emoji = "👄",
      exampleSentenceEn = "Smile happily with your mouth!",
      exampleSentenceSw = "Tabasamu kwa mdomo wako!",
      funFact = "Kiswahili words sound musical from the mdomo.",
    ),
    Flashcard(
      id = "body_5",
      english = "Ears",
      kiswahili = "Masikio",
      syllables = "MA • SI • KI • O",
      category = Category.BODY,
      emoji = "👂",
      exampleSentenceEn = "Listen carefully to the teacher.",
      exampleSentenceSw = "Sikiliza kwa makini kwa masikio yako.",
      funFact = "One ear is called 'Sikio'.",
    ),
    Flashcard(
      id = "body_6",
      english = "Hands",
      kiswahili = "Mikono",
      syllables = "MI • KO • NO",
      category = Category.BODY,
      emoji = "🙌",
      exampleSentenceEn = "Clap your hands together!",
      exampleSentenceSw = "Piga makofi kwa mikono yako!",
      funFact = "One hand is called 'Mkono'.",
    ),
    Flashcard(
      id = "body_7",
      english = "Legs / Feet",
      kiswahili = "Miguu",
      syllables = "MI • GU • U",
      category = Category.BODY,
      emoji = "🦶",
      exampleSentenceEn = "We jump and dance with our legs.",
      exampleSentenceSw = "Tunaruka na kucheza kwa miguu.",
      funFact = "One foot is 'Mguu'.",
    ),

    // Rangi / Colors
    Flashcard(
      id = "col_1",
      english = "Red",
      kiswahili = "Nyekundu",
      syllables = "NYE • KU • NDU",
      category = Category.COLORS,
      emoji = "🔴",
      exampleSentenceEn = "The ripe apple is bright red.",
      exampleSentenceSw = "Tufaha lililoiva ni jekundu.",
      funFact = "Red is in the Kenyan flag symbolizing courage!",
    ),
    Flashcard(
      id = "col_2",
      english = "Green",
      kiswahili = "Kijani",
      syllables = "KI • JA • NI",
      category = Category.COLORS,
      emoji = "🟢",
      exampleSentenceEn = "The leaves of the tree are fresh green.",
      exampleSentenceSw = "Majani ya mti ni ya kijani.",
      funFact = "Green in Kenya's flag stands for our rich land.",
    ),
    Flashcard(
      id = "col_3",
      english = "Black",
      kiswahili = "Nyeusi",
      syllables = "NYE • U • SI",
      category = Category.COLORS,
      emoji = "⚫",
      exampleSentenceEn = "The night sky is calm and black.",
      exampleSentenceSw = "Anga ya usiku ni nyeusi tulivu.",
      funFact = "Black represents the people of Kenya.",
    ),
    Flashcard(
      id = "col_4",
      english = "White",
      kiswahili = "Nyeupe",
      syllables = "NYE • U • PE",
      category = Category.COLORS,
      emoji = "⚪",
      exampleSentenceEn = "The fluffy cloud is white.",
      exampleSentenceSw = "Wingu lina rangi nyeupe.",
      funFact = "White signifies peace ('Amani') in Kenya.",
    ),
    Flashcard(
      id = "col_5",
      english = "Yellow",
      kiswahili = "Njano",
      syllables = "NJA • NO",
      category = Category.COLORS,
      emoji = "🟡",
      exampleSentenceEn = "The warm sun shines with bright yellow light.",
      exampleSentenceSw = "Jua linang'aa kwa rangi ya njano.",
      funFact = "Ripe sweet bananas turn bright njano!",
    ),
    Flashcard(
      id = "col_6",
      english = "Blue",
      kiswahili = "Bluu",
      syllables = "BLU • U",
      category = Category.COLORS,
      emoji = "🔵",
      exampleSentenceEn = "The ocean water is sparkling blue.",
      exampleSentenceSw = "Maji ya bahari yana rangi ya bluu.",
      funFact = "The Indian Ocean at Mombasa is deep bluu.",
    ),

    // Shuleni / School
    Flashcard(
      id = "sch_1",
      english = "Book",
      kiswahili = "Kitabu",
      syllables = "KI • TA • BU",
      category = Category.SCHOOL,
      emoji = "📖",
      exampleSentenceEn = "Open your story book.",
      exampleSentenceSw = "Fungua kitabu chako cha hadithi.",
      funFact = "Plural is 'Vitabu' (many books)!",
    ),
    Flashcard(
      id = "sch_2",
      english = "Pencil / Pen",
      kiswahili = "Kalamu",
      syllables = "KA • LA • MU",
      category = Category.SCHOOL,
      emoji = "✏️",
      exampleSentenceEn = "I write neatly with my pencil.",
      exampleSentenceSw = "Ninaandika vizuri kwa kalamu yangu.",
      funFact = "Kalamu can write letters and draw funny animals!",
    ),
    Flashcard(
      id = "sch_3",
      english = "Desk",
      kiswahili = "Dawati",
      syllables = "DA • WA • TI",
      category = Category.SCHOOL,
      emoji = "🪑",
      exampleSentenceEn = "Sit comfortably at your desk.",
      exampleSentenceSw = "Keti vizuri kwenye dawati lako.",
      funFact = "Classmates share a wide dawati in Grade 1.",
    ),
    Flashcard(
      id = "sch_4",
      english = "Teacher",
      kiswahili = "Mwalimu",
      syllables = "MWA • LI • MU",
      category = Category.SCHOOL,
      emoji = "👩‍🏫",
      exampleSentenceEn = "Mwalimu helps us learn every day.",
      exampleSentenceSw = "Mwalimu anatufundisha kwa upendo.",
      funFact = "Teachers are highly honored across East Africa!",
    ),

    // Chakula / Food
    Flashcard(
      id = "food_1",
      english = "Banana",
      kiswahili = "Ndizi",
      syllables = "NDI • ZI",
      category = Category.FOOD,
      emoji = "🍌",
      exampleSentenceEn = "A sweet ripe banana is healthy.",
      exampleSentenceSw = "Ndizi tamu iliyoiva ni afya.",
      funFact = "Kisii and Murang'a in Kenya grow sweet ndizi!",
    ),
    Flashcard(
      id = "food_2",
      english = "Water",
      kiswahili = "Maji",
      syllables = "MA • JI",
      category = Category.FOOD,
      emoji = "💧",
      exampleSentenceEn = "Drink clean water every day.",
      exampleSentenceSw = "Kunywa maji safi kila siku.",
      funFact = "'Maji ni uhai' means 'Water is life' in Swahili!",
    ),
    Flashcard(
      id = "food_3",
      english = "Milk",
      kiswahili = "Maziwa",
      syllables = "MA • ZI • WA",
      category = Category.FOOD,
      emoji = "🥛",
      exampleSentenceEn = "Milk makes our bones and teeth strong.",
      exampleSentenceSw = "Maziwa yanajenga mifupa yenye nguvu.",
      funFact = "Fresh cow milk is called 'Maziwa ya ng'ombe'.",
    ),
    Flashcard(
      id = "food_4",
      english = "Mango",
      kiswahili = "Embe",
      syllables = "E • MBE",
      category = Category.FOOD,
      emoji = "🥭",
      exampleSentenceEn = "Juicy mango is my favorite fruit.",
      exampleSentenceSw = "Embe lenye majimaji ni tunda nilipendalo.",
      funFact = "Plural is 'Maembe' (many mangoes)!",
    )
  )

  val stickers: List<Sticker> = listOf(
    Sticker(
      id = "stk_simba",
      nameSw = "Simba Hodari",
      nameEn = "Brave Lion Cub",
      badgeText = "Hodari!",
      cheerText = "🦁 ROAAR! Simba Hodari! Uko jasiri sana!",
      isUnlocked = true,
      drawableRes = R.drawable.sticker_simba,
    ),
    Sticker(
      id = "stk_twiga",
      nameSw = "Twiga Rafiki",
      nameEn = "Friendly Explorer",
      badgeText = "Vizuri!",
      cheerText = "🦒 Twiga Rafiki anajivunia bidii yako ya kusoma!",
      isUnlocked = true,
      drawableRes = R.drawable.sticker_twiga,
    ),
    Sticker(
      id = "stk_tembo",
      nameSw = "Tembo Shujaa",
      nameEn = "Mighty Elephant",
      badgeText = "Shujaa!",
      cheerText = "🐘 PAAAH! Tembo Mwenye Nguvu! Una akili nyingi!",
      isUnlocked = true,
      drawableRes = R.drawable.sticker_tembo,
    ),
    Sticker(
      id = "stk_nyota",
      nameSw = "Nyota Dhahabu",
      nameEn = "Golden Quiz Star",
      badgeText = "100% Ace",
      cheerText = "⭐ Hongera! Nyota ya Dhahabu kwa maswali yote!",
      isUnlocked = true,
      drawableRes = R.drawable.sticker_nyota,
    ),
    Sticker(
      id = "stk_kipepeo",
      nameSw = "Kipepeo Rangi",
      nameEn = "Colors Master",
      badgeText = "Rangi!",
      cheerText = "🦋 Kipepeo anapepea! Rangi zote zimeeleweka!",
      isUnlocked = true,
      drawableRes = R.drawable.sticker_kipepeo,
    ),
    Sticker(
      id = "stk_dawati",
      nameSw = "Dawati Safi",
      nameEn = "Classroom Words",
      badgeText = "Shule!",
      cheerText = "📚 Shule ni furaha! Umemaliza msamiati wa darasani!",
      isUnlocked = true,
      drawableRes = R.drawable.sticker_dawati,
    ),
    Sticker(
      id = "stk_ndizi",
      nameSw = "Ndizi Tamu",
      nameEn = "Food Explorer",
      badgeText = "Matunda!",
      cheerText = "🍌 Ndizi Tamu! Chakula chenye afya na nguvu!",
      isUnlocked = true,
      drawableRes = R.drawable.sticker_ndizi,
    ),
    Sticker(
      id = "stk_sungura",
      nameSw = "Sungura Mjanja",
      nameEn = "7-Day Streak",
      badgeText = "Siku 7!",
      cheerText = "🐰 Sungura Mjanja! Siku 7 mfululizo! Wewe ni hodari mno!",
      isUnlocked = true,
      drawableRes = R.drawable.sticker_sungura,
    ),
    Sticker(
      id = "stk_kiboko",
      nameSw = "Kiboko Mcheshi",
      nameEn = "Numbers Hero",
      badgeText = "Bado",
      cheerText = "🦛 Maliza nambari 1-10 kufungua Kiboko Mcheshi!",
      isUnlocked = false,
      drawableRes = R.drawable.twiga_mascot,
      requirementText = "Maliza Nambari 1–10",
    ),
    Sticker(
      id = "stk_kasa",
      nameSw = "Kasa Hodari",
      nameEn = "Curious Turtle",
      badgeText = "Bado",
      cheerText = "🐢 Jifunze maneno 10 zaidi kufungua Kasa Hodari!",
      isUnlocked = false,
      drawableRes = R.drawable.twiga_mascot,
      requirementText = "Jifunze Maneno 10 zaidi",
    ),
  )
}
